export type PresetName =
  | "thai-official-date"
  | "thai-official-date-with-weekday"
  | "thai-short-date"
  | "thai-slash-date"
  | "japanese-official"
  | "japanese-official-with-weekday"
  | "japanese-seireki"
  | "japanese-era-short"
  | "taiwan-official"
  | "us-standard"
  | "us-long"
  | "us-with-weekday"
  | "uk-standard"
  | "uk-long"
  | "uk-with-weekday"
  | "german-din-standard"
  | "german-long"
  | "german-with-weekday"
  | "french-standard"
  | "french-long"
  | "french-with-weekday"
  | "chinese-standard"
  | "chinese-with-weekday"
  | "chinese-short"
  | "spanish-standard"
  | "spanish-long"
  | "spanish-with-weekday"
  | "arabic-gregorian"
  | "arabic-hijri";

export type ThaiPresetName =
  | "thai-official-date"
  | "thai-official-date-with-weekday"
  | "thai-short-date"
  | "thai-slash-date";
